# analysis_options.yaml - Configuration professionnelle

include: package:flutter_lints/recommended.yaml

analyzer:
  # Activation de tous les diagnostics
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  
  # Configuration des erreurs et avertissements
  errors:
    # Erreurs critiques
    missing_required_param: error
    missing_return: error
    invalid_override: error
    dead_code: error
    
  # Règles spécifiques
  language:
    strict-raw-types: true
    strict-inference: true
  
  # Exclusions
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - ".dart_tool/**"
    - "**/generated/**"
  
  # Plugins supplémentaires
  plugins:
    - dart_code_metrics

linter:
  rules:
    # === SÉCURITÉ ===
    - use_key_in_widget_constructors: error
    - avoid_print: warning
    - avoid_web_libraries_in_flutter: error
    
    # === PERFORMANCE ===
    - prefer_const_constructors: warning
    - prefer_const_constructors_in_immutables: warning
    - prefer_const_literals_to_create_immutables: warning
    - avoid_unnecessary_containers: warning
    - sized_box_for_whitespace: warning
    
    # === QUALITÉ DU CODE ===
    # Dart de base
    - always_declare_return_types: warning
    - always_require_non_null_named_parameters: warning
    - avoid_dynamic_calls: warning
    - avoid_void_async: error
    - camel_case_types: warning
    - constant_identifier_names: warning
    - empty_constructor_bodies: warning
    - library_names: warning
    - library_prefixes: warning
    - no_duplicate_case_values: error
    - null_closures: error
    - prefer_final_fields: warning
    - prefer_final_in_for_each: warning
    - prefer_final_locals: warning
    - prefer_foreach: warning
    - prefer_if_null_operators: warning
    - type_init_formals: warning
    - unnecessary_const: warning
    - use_function_type_syntax_for_parameters: warning
    - use_late_for_private_fields_and_variables: warning
    - use_named_constants: warning
    
    # Flutter spécifique
    - always_specify_types: warning
    - annotate_overrides: warning
    - avoid_equals_and_hash_code_on_mutable_classes: warning
    - avoid_function_literals_in_foreach_calls: warning
    - avoid_redundant_argument_values: warning
    - avoid_relative_lib_imports: warning
    - avoid_renaming_method_parameters: warning
    - avoid_returning_this: warning
    - avoid_shadowing_type_parameters: warning
    - avoid_single_cascade_in_expression_statements: warning
    - avoid_type_to_string: warning
    - avoid_unused_constructor_parameters: warning
    - await_only_futures: error
    - curly_braces_in_flow_control_structures: warning
    - deprecated_consistency: warning
    - empty_statements: warning
    - invariant_booleans: warning
    - join_return_with_assignment: warning
    - leading_newlines_in_multiline_strings: warning
    - library_annotations: warning
    - no_runtimeType_toString: error
    - only_throw_errors: error
    - overridden_fields: warning
    - package_api_docs: warning
    - package_names: warning
    - package_prefixed_library_names: warning
    - prefer_adjacent_string_concatenation: warning
    - prefer_asserts_in_initializer_lists: warning
    - prefer_conditional_assignment: warning
    - prefer_const_declarations: warning
    - prefer_double_quotes: warning
    - prefer_equal_for_default_values: warning
    - prefer_is_empty: warning
    - prefer_is_not_empty: warning
    - prefer_spread_collections: warning
    - prefer_typing_uninitialized_variables: warning
    - provide_deprecation_message: warning
    - recursive_getters: error
    - require_trailing_commas: warning
    - sort_child_properties_last: warning
    - type_annotate_public_apis: warning
    - unawaited_futures: warning
    - unnecessary_await_in_return: warning
    - unnecessary_brace_in_string_interps: warning
    - unnecessary_getters_setters: warning
    - unnecessary_lambdas: warning
    - unnecessary_new: warning
    - unnecessary_null_checks: warning
    - unnecessary_nullable_for_final_variable_declarations: warning
    - unnecessary_parenthesis: warning
    - unnecessary_raw_strings: warning
    - unnecessary_statements: warning
    - unnecessary_string_escapes: warning
    - unnecessary_string_interpolations: warning
    - unnecessary_this: warning
    - use_build_context_synchronously: error
    - use_full_hex_values_for_flutter_colors: warning
    - use_rethrow_when_possible: warning
    - use_setters_to_change_properties: warning
    - use_string_buffers: warning
    - use_super_parameters: warning
    - valid_regexps: error

# Configuration de dart_code_metrics (optionnel)
dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 5
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - no-magic-number:
        allowed: [0, 1, 2, 10, 100, 1000, 24, 60, 3600, 12, 52, 365]
    - member-ordering:
        order:
          - constructors
          - public-fields
          - private-fields
          - public-getters
          - private-getters
          - public-setters
          - private-setters
          - public-methods
          - private-methods
    - prefer-trailing-comma: error
    - no-empty-block: warning
    - no-object-declaration: warning